#
# Dockerfile for sonarqube-base-win
#

FROM frozenbytes/chocolatey:0.0.5-alpha
MAINTAINER frozenbytes

# Setup one or more individual labels
LABEL com.i-m-code.sonarqube-base-win.version="0.0.4-alpha" \
	  com.i-m-code.sonarqube-base-win.release-date="1-26-2017" \
	  com.i-m-code.sonarqube-base-win.license="MIT" \
	  com.i-m-code.sonarqube-base-win.repo="sonarqube-base-win" \
	  com.i-m-code.sonarqube-base-win.baserepo="frozenbytes"