#
# Docker Compose for docker__CONTAINER_NAME__
#
#
# Must Set Restart Policy
#
 image: 'docker__IMAGE_NAME__'
  container_name: docker__CONTAINER_NAME__
  restart: <no|on-failure|unless-stopped|always>
  environment:
    - VIRTUAL_HOST=docker__SUB_NET_NAME__.itascahub.com
    - VIRTUAL_PORT=9000
    - docker__CONTAINER_NAME___JDBC_URL=jdbc:postgresql://docker__CONTAINER_NAME___db_1:5432/docker__SUB_NET_NAME__
  links:
     - docker__CONTAINER_NAME___db_1
  volumes:
    - /data/docker__CONTAINER_NAME__/conf:/opt/docker__CONTAINER_NAME__/conf
    - /data/docker__CONTAINER_NAME__/data:/opt/docker__CONTAINER_NAME__/data
    - /data/docker__CONTAINER_NAME__/extensions:/opt/docker__CONTAINER_NAME__/extensions
    - /data/docker__CONTAINER_NAME__/bundled-plugins:/opt/docker__CONTAINER_NAME__/lib/bundled-plugins

docker__CONTAINER_NAME___db_1:
  image: postgres
  container_name: docker__CONTAINER_NAME___db_1
  environment:
    - POSTGRES_USER=docker__SUB_NET_NAME__
    - POSTGRES_PASSWORD=docker__SUB_NET_NAME__
  volumes:
    - /data/docker__CONTAINER_NAME__/postgresql/data/:/var/lib/postgresql/data
    - /data/docker__CONTAINER_NAME__/postgresql_data/:/var/lib/postgresqldata