#
# Dockerfile for sonarqube-win
#

FROM frozenbytes/chocolatey:0.0.3-alpha
MAINTAINER frozenbytes

# Setup Environment Variables
# ENV APPDIR <DIR>

# Setup one or more individual labels
LABEL com.i-m-code.sonarqube-win.version="0.0.2-alpha" \
	  com.i-m-code.sonarqube-win.release-date="1-21-2017" \
	  com.i-m-code.sonarqube-win.license="MIT" \
	  com.i-m-code.sonarqube-win.repo="sonarqube-win" \
	  com.i-m-code.sonarqube-win.baserepo="frozenbytes"

# Startup Policy MUST BE SET in COMPOSE file

# Install Oracle JRE8 8
# RUN powershell ($env:Path).Split(";") | Sort-Object
# RUN powershell CINST jre8 -y
# RUN powershell echo ($env:Path).Split(";") | Sort-Object
CMD Path

# Install SonarQube based on SONAR_VERSION
# 

# Install Sonarqube Plugins
# CSS, JSON, # JavaScript



    # TODO: Sonar Web Frontend Plugin
    # https://github.com/groupe-sii/sonar-web-frontend-plugin

# Install Sonarqube Default Languages
# C#, Java, Python, Javascript, HTML, CSS, web, XML, VB.NET
#

# Install Sonar Scanner
# Latest version as of December 2016 Compatible with SonarQube 5.6+ (LTS)
# https://docs.sonarqube.org/display/SCAN/Analyzing+Source+Code
#


# Setup Sample Scan of .NET Project from sonar online
# https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner
# https://sonarqube.com/projects


#WORKDIR C:/sonarqube
#ENTRYPOINT ["C:\\sonarqube\\bin\\run.cmd"]


